static const char *ddcaps[32] = {
"DDCAPS_3D", "DDCAPS_ALIGNBOUNDARYDEST", "DDCAPS_ALIGNSIZEDEST", "DDCAPS_ALIGNBOUNDARYSRC", 
"DDCAPS_ALIGNSIZESRC", "DDCAPS_ALIGNSTRIDE", "DDCAPS_BLT", "DDCAPS_BLTQUEUE", "DDCAPS_BLTFOURCC", 
"DDCAPS_BLTSTRETCH", "DDCAPS_GDI", "DDCAPS_OVERLAY", "DDCAPS_OVERLAYCANTCLIP", "DDCAPS_OVERLAYFOURCC", 
"DDCAPS_OVERLAYSTRETCH", "DDCAPS_PALETTE", "DDCAPS_PALETTEVSYNC", "DDCAPS_READSCANLINE", 
"DDCAPS_RESERVED1", "DDCAPS_VBI", "DDCAPS_ZBLTS", "DDCAPS_ZOVERLAYS", "DDCAPS_COLORKEY", 
"DDCAPS_ALPHA", "DDCAPS_COLORKEYHWASSIST", "DDCAPS_NOHARDWARE", "DDCAPS_BLTCOLORFILL", 
"DDCAPS_BANKSWITCHED", "DDCAPS_BLTDEPTHFILL", "DDCAPS_CANCLIP", "DDCAPS_CANCLIPSTRETCHED", 
"DDCAPS_CANBLTSYSMEM"};

static const char *ddcaps2[32] = {
"DDCAPS2_CERTIFIED", "DDCAPS2_NO2DDURING3DSCENE", "DDCAPS2_VIDEOPORT", "DDCAPS2_AUTOFLIPOVERLAY", 
"DDCAPS2_CANBOBINTERLEAVED", "DDCAPS2_CANBOBNONINTERLEAVED", "DDCAPS2_COLORCONTROLOVERLAY", 
"DDCAPS2_COLORCONTROLPRIMARY", "DDCAPS2_CANDROPZ16BIT", "DDCAPS2_NONLOCALVIDMEM", 
"DDCAPS2_NONLOCALVIDMEMCAPS", "DDCAPS2_NOPAGELOCKREQUIRED", "DDCAPS2_WIDESURFACES", 
"DDCAPS2_CANFLIPODDEVEN", "DDCAPS2_CANBOBHARDWARE", "DDCAPS2_COPYFOURCC", "DDCAPS2_UNKNOWN", 
"DDCAPS2_PRIMARYGAMMA", "DDCAPS2_UNKNOWN", "DDCAPS2_CANRENDERWINDOWED", "DDCAPS2_CANCALIBRATEGAMMA", 
"DDCAPS2_FLIPINTERVAL", "DDCAPS2_FLIPNOVSYNC", "DDCAPS2_CANMANAGETEXTURE", "DDCAPS2_TEXMANINNONLOCALVIDMEM", 
"DDCAPS2_STEREO", "DDCAPS2_SYSTONONLOCAL_AS_SYSTOLOCAL", "DDCAPS2_PUREHAL"};

static const char *ddfxcaps[32] = {
"DDFXCAPS_BLTALPHA", "DDFXCAPS_UNKNOWN", "DDFXCAPS_OVERLAYALPHA", "DDFXCAPS_OVERLAYARITHSTRETCHYN", 
"DDFXCAPS_BLTARITHSTRETCHYN", "DDFXCAPS_BLTARITHSTRETCHY", "DDFXCAPS_BLTMIRRORLEFTRIGHT", 
"DDFXCAPS_BLTMIRRORUPDOWN", "DDFXCAPS_BLTROTATION", "DDFXCAPS_BLTROTATION90", "DDFXCAPS_BLTSHRINKX", 
"DDFXCAPS_BLTSHRINKXN", "DDFXCAPS_BLTSHRINKY", "DDFXCAPS_BLTSHRINKYN", "DDFXCAPS_BLTSTRETCHX", 
"DDFXCAPS_BLTSTRETCHXN", "DDFXCAPS_BLTSTRETCHY", "DDFXCAPS_BLTSTRETCHYN", "DDFXCAPS_OVERLAYARITHSTRETCHY", 
"DDFXCAPS_OVERLAYSHRINKX", "DDFXCAPS_OVERLAYSHRINKXN", "DDFXCAPS_OVERLAYSHRINKY", 
"DDFXCAPS_OVERLAYSHRINKYN", "DDFXCAPS_OVERLAYSTRETCHX", "DDFXCAPS_OVERLAYSTRETCHXN", 
"DDFXCAPS_OVERLAYSTRETCHY", "DDFXCAPS_OVERLAYSTRETCHYN", "DDFXCAPS_OVERLAYMIRRORLEFTRIGHT", 
"DDFXCAPS_OVERLAYMIRRORUPDOWN", "DDFXCAPS_OVERLAYDEINTERLACE"};

static const char *ddckeycaps[32] = {
"DDCKEYCAPS_DESTBLT", "DDCKEYCAPS_DESTBLTCLRSPACE", "DDCKEYCAPS_DESTBLTCLRSPACEYUV", 
"DDCKEYCAPS_DESTBLTYUV", "DDCKEYCAPS_DESTOVERLAY", "DDCKEYCAPS_DESTOVERLAYCLRSPACE", 
"DDCKEYCAPS_DESTOVERLAYCLRSPACEYUV", "DDCKEYCAPS_DESTOVERLAYONEACTIVE", "DDCKEYCAPS_DESTOVERLAYYUV", 
"DDCKEYCAPS_SRCBLT", "DDCKEYCAPS_SRCBLTCLRSPACE", "DDCKEYCAPS_SRCBLTCLRSPACEYUV", 
"DDCKEYCAPS_SRCBLTYUV", "DDCKEYCAPS_SRCOVERLAY", "DDCKEYCAPS_SRCOVERLAYCLRSPACE", 
"DDCKEYCAPS_SRCOVERLAYCLRSPACEYUV", "DDCKEYCAPS_SRCOVERLAYONEACTIVE", "DDCKEYCAPS_SRCOVERLAYYUV", 
"DDCKEYCAPS_NOCOSTOVERLAY"};

static const char *ddscaps[32] = {
"DDSCAPS_RESERVED1", "DDSCAPS_ALPHA", "DDSCAPS_BACKBUFFER", "DDSCAPS_COMPLEX", "DDSCAPS_FLIP", 
"DDSCAPS_FRONTBUFFER", "DDSCAPS_OFFSCREENPLAIN", "DDSCAPS_OVERLAY", "DDSCAPS_PALETTE", 
"DDSCAPS_PRIMARYSURFACE", "DDSCAPS_RESERVED3", "DDSCAPS_SYSTEMMEMORY", "DDSCAPS_TEXTURE", 
"DDSCAPS_3DDEVICE", "DDSCAPS_VIDEOMEMORY", "DDSCAPS_VISIBLE", "DDSCAPS_WRITEONLY", 
"DDSCAPS_ZBUFFER", "DDSCAPS_OWNDC", "DDSCAPS_LIVEVIDEO", "DDSCAPS_HWCODEC", "DDSCAPS_MODEX", 
"DDSCAPS_MIPMAP", "DDSCAPS_RESERVED2", "DDSCAPS_UNKNOWN", "DDSCAPS_UNKNOWN", "DDSCAPS_ALLOCONLOAD", 
"DDSCAPS_VIDEOPORT", "DDSCAPS_LOCALVIDMEM", "DDSCAPS_NONLOCALVIDMEM", "DDSCAPS_STANDARDVGAMODE", 
"DDSCAPS_OPTIMIZED"};

static void Dprintf(char *fmt, ...)
{
	char s[1000], *p;
	TCHAR path[MAX_PATH], *tp;
	HANDLE h;
	DWORD bw;
	va_list ap;
	SYSTEMTIME t;

	GetLocalTime(&t);
	*s = 0;
	p = s;
	va_start(ap, fmt);
	vsprintf(p, fmt, ap);
	va_end(ap);
	strcat(s, "\r\n");
	GetModuleFileName(0, path, MAX_PATH);
	tp = _tcschr(path, '\\');
	if(tp)
	{
		_tcscpy(tp + 1, TEXT("ddcaps.txt"));
		h = CreateFile(path, GENERIC_WRITE, FILE_SHARE_WRITE | FILE_SHARE_READ, 0, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, 0);
		if(h != INVALID_HANDLE_VALUE)
		{
			SetFilePointer(h, 0, 0, FILE_END);
			WriteFile(h, s, strlen(s), &bw, 0);
			CloseHandle(h);
		}
	}
}

static void printcaps2(DWORD caps, const char **descs)
{
	int i;

	for(i = 0; i < 32; i++)
		if(caps & (1 << i))
			if(descs[i])
				Dprintf("%s", descs[i]);
			else Dprintf("UKNOWN");
}

static void printcaps(DDCAPS *ddc)
{
#ifndef _WIN32_WCE
	printcaps2(ddc->dwCaps, ddcaps);
	printcaps2(ddc->dwCaps2, ddcaps2);
	printcaps2(ddc->dwFXCaps, ddfxcaps);
#endif
	printcaps2(ddc->dwCKeyCaps, ddckeycaps);
	printcaps2(ddc->ddsCaps.dwCaps, ddscaps);
}
