#ifndef CODEC_GSM
#define CODEC_GSM 0
#define CODEC_MSGSM 0
#define CODEC_TRUESPEECH 1
#define CODEC_G723 2
#define CODEC_SPEEXA 3
#define CODEC_SPEEXB 4
#define CODEC_SPEEXC 5
#define CODEC_SPEEXD 6
#define CODEC_SPEEXE 7
#define CODEC_GSMFR 8
#define CODEC_G729 9
#define CODEC_G711A 0xa
#define CODEC_G711U 0xb
#define CODEC_ILBC30 0xc
#define CODEC_ILBC20 0xd
#define CODEC_LINEARBE 0xe
#define CODEC_LINEARLE 0xf
#define CODEC_LAST CODEC_G711U
#endif

#define PKT_FT 0x7f
#define PKT_VIDEO 0x7e
#define PKT_AUDIOPARITY 0x7d
#define PKT_VIDEOPARITY 0x7c

#define IE_CONNECTIONID 0
#define IE_BEARER 1
#define IE_ANSWER 2
#define IE_REASON 3
#define IE_SOURCENUMBER 4
#define IE_SOURCENAMEDEPRECATED 5
#define IE_SOURCESUBADDRESS 6
#define IE_DESTNUMBER 7
#define IE_DESTSUBADDRESS 8
#define IE_MESSAGE 9
#define IE_FILENAME 10
#define IE_DEFLECTTONUMBER 11
#define IE_SEQNUMBER 12
#define IE_VIDEOFMT 13
#define IE_FILLER 14
#define IE_MTU 15
#define IE_FILELENGTH 16
#define IE_FILECRC 17
#define IE_STARTPOS 18
#define IE_INADDR_HOST 19
#define IE_INADDR_PRIVATE 20
#define IE_INADDR_PUBLIC 21
#define IE_SERVERACCESSCODE 22
#define IE_VERSION 23
#define IE_CALLREQUEST 24
#define IE_OPERATION 25
#define IE_TOKEN 26
#define IE_MULTIINADDR_HOST 27
#define IE_CONFSETUPSTEP 28
#define IE_TEXT 29
#define IE_NFILES 30
#define IE_NBYTES 31
#define IE_FILESLIST 32
#define IE_CALLTRANSFER 33
#define IE_CALLSTATUS 34
#define IE_MISSEDCALL 35
#define IE_KEYPAD 36
#define IE_CODEPAGE 37
#define IE_AUTHDATA 38
#define IE_ENCODEDNUMBERS 39
#define IE_OFFLINE 40
#define	IE_TIMESTAMP 41
#define IE_SERVERID 42
#define IE_USERSTATUS 43
#define IE_INADDR_REQUESTER 44
#define IE_INADDR_REQUESTER2 45
#define IE_SESSIONID 46
#define IE_SESSIONSECRET 47
#define IE_SERVERSLIST 48
#define IE_FIRSTNAME 49
#define IE_LASTNAME 50
#define IE_AGEGROUP 51
#define IE_GENDER 52
#define IE_COUNTRYID 53
#define IE_ZIP 54
#define IE_CITY 55	
#define IE_SERIAL 56
#define IE_DESTNAME 57
#define IE_TRANSPARENTDATA 58
#define IE_COUNTERS 59
#define IE_SOURCENAME 60
#define IE_PROTVERSION 61
#define IE_CALLID 62
#define IE_QUOTA 63
#define IE_GREETINGPATH 64
#define IE_SMSQUOTA 65
#define IE_EMAIL 66
#define IE_PHONENUMBER 67
#define IE_SMSTYPE 68
#define IE_SMSID 69
#define IE_EXPIRATION 70

#define TEXTENC_PLAIN 0
#define TEXTENC_RTF1 1

#define ANSWER_REFUSE 0
#define ANSWER_ACCEPT 1
#define ANSWER_USERALERTED 2
#define ANSWER_INITIATED 3

#define OPERATION_ASK 0
#define OPERATION_DEACTIVATE 1
#define OPERATION_ACTIVATE 2
#define OPERATION_ACTIVATE_ONOFFLINE 3

#define REASON_NORMAL 0
#define REASON_BEARER_NOT_SUPPORTED 1
#define REASON_CODEC_NOT_SUPPORTED 2
#define REASON_CALLPROCESSING 3
#define REASON_MISSINGCLID 4
#define REASON_CALLDEFLECTION 5
#define REASON_BUSY 6
#define REASON_FILESAME 7
#define REASON_TIMEOUT 8	
#define REASON_DISCONNECTED 9
#define REASON_AUTHERROR 10
#define REASON_NOTFOUND 11
#define REASON_SYNTAXERROR 12
#define REASON_INVALIDNUMBER 13
#define REASON_STORAGEEXCEEDED 14
#define REASON_ALREADYCONNECTED 15
#define REASON_PROTOCOLNOTSUPPORTED 16
#define REASON_SERVERREDIRECTION 17
#define REASON_ADMINERROR 18
#define REASON_ACCOUNTBLOCKED 19
#define REASON_CALLTRANSFERCOMPLETE 20
#define REASON_NOQUOTA 21
#define REASON_USEROFFLINE 22
#define REASON_SERVERNOTRESPONDING 23
#define REASON_SERVERNOTRUNNING 24
#define REASON_VPHONENOTRESPONDING 25
#define REASON_VPHONENOTRUNNING 26
#define REASON_CALLPROCEEDING 27
#define REASON_CONNECTIONLOST 28
#define REASON_WRONGVERSION 29
#define REASON_EARLYAUDIO 30
#define REASON_ANOTHERPORT 31
#define REASON_ANOTHERADDR 32
#define REASON_CANNOTNOTIFY 33
#define REASON_NOTKNOWN 34
#define REASON_LOOPCALL 35
#define REASON_VOICE2VIDEO 36	// Not used internally by VPSTACK
#define REASON_NORESOURCES 37

#define BC_VOICE 0
#define BC_AUDIOVIDEO 1
#define BC_CHAT 2
#define BC_SMS 3
#define BC_FILE 4
#define BC_VIDEO 5
#define BC_VIDEOMSG 6
#define BC_LAST 6
#define BC_NOTHING 31

#define PKT_CONNECTREQ 0x80
#define PKT_CONNECTACK 0x81
#define PKT_CONNECTACK_RECEIVED 0x82
#define PKT_DISCONNECTREQ 0x83
#define PKT_CHAT 0x84
#define PKT_CHATACK 0x85
#define PKT_AWAKE 0x86
#define PKT_RECVFILEREQ 0x87
#define PKT_CALLSTATUS 0x88
#define PKT_GENERALACK 0x89
#define PKT_MTUTEST 0x8a
#define PKT_SENDFILEREQ 0x8b
#define PKT_SENDFILEACK 0x8c
#define PKT_FILEINFO 0x8d
#define PKT_SENDFILEEND 0x8e
#define PKT_SENDFILEENDACK 0x8f

#define PKT_NOTIFY 0x90
#define PKT_NOTIFYACK 0x91
#define PKT_QUERYADDR 0x92
#define PKT_QUERYADDRACK 0x93
#define PKT_CALLREQUEST 0x94
#define PKT_CALLREQUESTACK 0x95
#define PKT_CALLFORWARDING 0x96
#define PKT_CALLFORWARDINGACK 0x97
#define PKT_NOTIFYDISC 0x98
#define PKT_QUERYONLINE 0x99
#define PKT_QUERYONLINEACK 0x9a
#define PKT_ACTIVATEACCOUNT 0x9b
#define PKT_ACTIVATEACCOUNTACK 0x9c
#define PKT_NATDISCOVER 0x9d
#define PKT_CHECKOFFLINEDATA 0x9e
#define PKT_NATDISCOVERACK 0x9f

#define PKT_INFO 0xa0
#define PKT_CONFERENCEREQ 0xa1
#define PKT_CONFERENCEACK 0xa2
#define PKT_CONFERENCECALL 0xa3
#define PKT_CONFERENCEEND 0xa4
#define PKT_CALLTRANSFER 0xa5
#define PKT_DROPCONFERENCEPEER 0xa6
#define PKT_KEYPAD 0xa7
#define PKT_ECHO 0xa8
#define PKT_ECHOACK 0xa9
#define PKT_NATDISCOVERFWD 0xaa
#define PKT_NOTIFYLOGON 0xab
#define PKT_NOTIFYLOGONACK 0xac
#define PKT_QUERYNAME 0xad
#define PKT_QUERYNAMEACK 0xae
#define PKT_SENDCOUNTERS 0xaf

#define PKT_DISCONNECTACK 0xb0
#define PKT_GETAUTHCALLDATA 0xb1
#define PKT_GETAUTHCALLDATAACK 0xb2
#define PKT_AUTHCALLCOMPLETE 0xb3
#define PKT_SENDACCOUNTINFO 0xb4
#define PKT_ACCOUNTINFO 0xb5
#define PKT_PROXYBIND 0xb6
#define PKT_PROXYBINDACK 0xb7

#define MAXNUMBERLEN 50
#define MAXADDRLEN 50
#define MAXSUBADDRLEN 30
#define MAXNAMELEN 50
#define MAXSERVERACCESSCODELEN 15
#define MAXACCOUNTDATALEN 30
#define MAXMESSAGELEN 400
#define MAXFILENAMELEN 255
#define MAXTEXTLEN 500
#define MAXSESSIONIDLEN 20
#define MAXSESSIONSECRETLEN 20
#define MAXVPARTIES 7

#define SMSTYPE_NORMAL 0	// Regular text SMS
#define SMSTYPE_MISSEDCALLS 1	// Missed calls SMS, use GetMissedCallsData()
#define SMSTYPE_DELIVERYREPORT 2	// Delivery report of a transmitted SMS (when transmitted to the server)
#define SMSTYPE_CONTACTADDED 3	// The sender has added the recipient to his contacts list
#define SMSTYPE_CONTACTADDED_ACK 4	// The sender has accepted the invitation and added the recipient in his contacts list
#define SMSTYPE_CONTACTADDED_NACK 5	// The sender has not accepted the invitation and not added the recipient in his contacts list
#define SMSTYPE_NEWFILE 6	// A new file is available on the server for download
#define SMSTYPE_FILEDELIVERED 7	//	The file has been downloaded from the server by the final user
